import React from 'react';

interface ActionProps {
    title?: string;
    onAction?: () => void;
}

export const Action: React.FC<ActionProps> = ({ title = 'Action', onAction }) => {
    return (
        <div className="p-8 bg-[#0a0a0f] text-white rounded-2xl border border-[#2a2a35]">
            <h2 className="text-4xl font-semibold tracking-tighter mb-4">{title}</h2>
            <p className="text-[#a0a0b0] mb-6">
                This React component was auto-generated by Kairos Coder for your goal:
                <br />
                <span className="text-[#00ffcc] font-mono text-sm">"create a react tsx button component called ActionButton"</span>
            </p>
            <button 
                onClick={onAction}
                className="px-6 py-3 bg-[#00ffcc] text-black rounded-xl font-medium hover:bg-white transition-colors"
            >
                Trigger Action
            </button>
        </div>
    );
};

export default Action;
