"""agents/scribe.py
Scribe agent: documents everything, updates soul.md, auto-generates reusable YAML skills from successful runs.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Callable, Optional

from core.tools import ClawTools
from hermes.memory import HermesMemory

logger = logging.getLogger("agents.scribe")


@dataclass
class AgentResult:
    success: bool
    output: str
    artifacts: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)


class Scribe:
    name = "scribe"
    SYSTEM_PROMPT = "You are a technical writer and knowledge engineer. Capture lessons, pitfalls, and procedures into reusable skills."

    def __init__(
        self,
        tools: ClawTools,
        memory: HermesMemory,
        llm_call: Optional[Callable[[str, str], str]] = None,
    ):
        self.tools = tools
        self.memory = memory
        self.llm_call = llm_call

    def run(self, goal: str, context: str = "") -> AgentResult:
        logger.info(f"SCRIBE capturing knowledge for: {goal[:60]}...")
        artifacts = []

        ts = datetime.now().strftime("%Y%m%d-%H%M")
        skill_name = f"skill-{ts}.yaml"
        skill_path = f"hermes/skills/{skill_name}"

        # Auto-generate a rich YAML skill from the successful execution
        skill_content = f"""# Auto-generated by HermesClaw Scribe
# Goal: {goal}
# Timestamp: {ts}
# This skill can be loaded by future agents for similar tasks.

name: "{goal[:60]}"
category: "swarm-task"
success_threshold: 0.85

procedure:
  - "1. Architect produces design doc"
  - "2. Coder implements using tools.write_file + tools.edit_file"
  - "3. Tester runs pytest + syntax checks"
  - "4. Scribe captures this YAML + updates soul.md"

pitfalls:
  - "Never bypass approval gates for destructive operations"
  - "Always use memory.get_relevant_context before starting new work"

verification:
  - "All Python files parse without syntax errors"
  - "Task outcome stored in HermesMemory with success=True"
  - "New skill file appears in hermes/skills/"

examples:
  - goal: "Add hello world example"
    outcome: "Created examples/hello_swarm.py and passed all checks"
"""
        write_res = self.tools.write_file(skill_path, skill_content)
        if write_res.get("success"):
            artifacts.append(skill_path)

        # Update soul.md with latest preference / learning
        soul_path = "hermes/soul.md"
        existing = self.tools.read_file(soul_path).get("output", "")
        soul_update = f"\n\n## {ts}\nLearned from goal: {goal}\nKey outcome: {context[:300]}\n"
        self.tools.write_file(soul_path, (existing + soul_update).strip())

        artifacts.append(soul_path)

        logger.info(f"SCRIBE created skill + updated soul: {skill_path}")

        return AgentResult(
            success=True,
            output=f"Knowledge captured. New skill: {skill_path}\nSoul.md updated.",
            artifacts=artifacts,
            metadata={"phase": "documentation", "skills_generated": 1},
        )
